"""bundles

Revision ID: 34f45e6817a
Revises: 52d9e7b917f
Create Date: 2015-01-08 11:37:26.622883

"""

# revision identifiers, used by Alembic.
revision = '34f45e6817a'
down_revision = '52d9e7b917f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_path', sa.String(length=512), nullable=False),
    sa.Column('bundle_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bundle')
    ### end Alembic commands ###
