"""project_settings

Revision ID: 52d9e7b917f
Revises: 4918c57ece7
Create Date: 2014-11-07 11:15:13.057416

"""

# revision identifiers, used by Alembic.
revision = '52d9e7b917f'
down_revision = '4918c57ece7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_setting')
    ### end Alembic commands ###
